name: workflow1 + My build action requiring more space
on: [workflow_dispatch] #[push]

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"
          df -h

#______________________________________________________________________

      - name: Checkout the code/initialize repo for use
        uses: actions/checkout@v2

#      - name: Open working temp dir
#        working-directory: temp

#      - name: Installing Dependencies
#        run: sudo apt-get install -y git && sudo apt install -y python2 && sudo apt install -y python3

      - name: ls + dir
        #working-directory: temp
        run: ls -la #ls && dir

      - name: make bromite-builder executable
        run: sudo chmod +x ./bromite-builder

      - name: fetch git for later checkout/fix it # propably BS
        run: git fetch && git remote update

      - name: Build the app
#        working-directory: temp
        run: ./bromite-builder --arch=arm --bromite-git-url="https://github.com/Mafiadoener36/bromite2.git" --dark-navbar --ubuntu-install-build-deps

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: debug apk
          path: out/