name: workflow0

on: [push] #[workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code/initialize repo for use
        uses: actions/checkout@v2

#      - name: Open working temp dir
#        working-directory: temp

      - name: Installing Dependencies
        run: sudo apt-get install -y git && sudo apt install -y python2 && sudo apt install -y python3

      - name: ls + dir
        working-directory: temp
        run: ls -la #ls && dir

      - name: make bromite-builder executable
        run: sudo chmod +x ./bromite-builder

      - name: fetch git for later checkout/fix it # propably BS
        run: git fetch && git remote update

      - name: Build the app
#        working-directory: temp
        run: ./bromite-builder --arch=arm --dark-navbar --ubuntu-install-build-deps

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: debug apk
          path: out/
